#!/bin/bash

install()
{
    if [[ -d "$TARGET/static" ]]
    then
	cd "$TARGET/static"
	
	echo "Backing up Original Files..."
	  mv -v $GW_CSS "$GW_CSS.bak"
	  mv -v $GW_JS "$GW_JS.bak"
	  mv -v $GW_ICON "$GW_ICON.bak"
	  mv -v $GW_LOGO "$GW_LOGO.bak"

	echo "Symlinking New Themed Files..."
	  ln -s "$THEME/$GW_CSS"
          ln -s "$THEME/$GW_JS"
          ln -s "$THEME/$GW_ICON"
          ln -s "$THEME/$GW_LOGO"

	echo "Complete!"
    else
	echo "Error: Could not locate the 'static' folder within '$TARGET'"
    fi
}

usage()
{
cat << EOF
Usage: $0 install
Or:    $0 install -t [GITWEB_INSTALL_DIR]
Or:    $0 remove
Or:    $0 remove -t [GITWEB_INSTALL_DIR]

This script will create symlinks to your gitweb install for themeing.
The default location is '/usr/share/gitweb' unless set via '-t'

OPTIONS:
  -h        Show this message
  -t        Target directory of gitweb install

ACTIONS:
  install   Adds '.bak' to original files and creates symlinks to new files
  remove    Deletes the symlinks and restores the original files.
EOF
}



# ======================= BEGIN =========================
TARGET="/usr/share/gitweb"
THEME=`pwd`
GW_CSS="gitweb.css"
GW_JS="gitweb.js"
GW_ICON="git-favicon.png"
GW_LOGO="git-logo.png"

while getopts "hl:v" OPTION
do
     case $OPTION in
         h  ) usage; exit 1;;
         t  ) TARGET=$OPTARG;;
         \? ) echo "Unknown option: -$OPTARG" >&2; usage; exit 1;;
         :  ) echo "Missing option argument for -$OPTARG" >&2; usage; exit 1;;
         *  ) echo "Unimplimented option: -$OPTARG" >&2; usage; exit 1;; 
    esac
done

case $1 in
    install ) install;;
    remove  ) ;;
    *       ) usage; exit 1;;    
esac

exit 0
