#!/bin/bash


##########################################################
#   Configuration
##########################################################
#
# Here you can set the default installation directory
# 
DEFAULT_TARGET="/usr/share/gitweb"




##########################################################
#   Functions
##########################################################
#
# (no need to modify, unless you want to)
#
install()
{
	set_target
	set_cmd_args
	
	if [[ $(check_if_themed) == $TRUE ]];
	then
		echo "Symlinks found in target (Is the theme already installed?)"
	else
		log ""
		if [[ $INTERACTIVE && $(confirm "Backing up Original Files, Continue?") == $FALSE ]]; then
			echo ""
			exit 1
		else
			mv $MV_ARGS "$TARGET/$GW_CSS" "$TARGET/$GW_CSS.bak"
			mv $MV_ARGS "$TARGET/$GW_JS" "$TARGET/$GW_JS.bak"
			mv $MV_ARGS "$TARGET/$GW_ICON" "$TARGET/$GW_ICON.bak"
			mv $MV_ARGS "$TARGET/$GW_LOGO" "$TARGET/$GW_LOGO.bak"
		fi
		
		log ""
		if [[ $INTERACTIVE && $(confirm "Symlinking New Themed Files, Continue?") == $FALSE ]]; then
			echo ""
			exit 1
		else
			ln $LN_ARGS "$THEME/$GW_CSS" "$TARGET/$GW_CSS"
			ln $LN_ARGS "$THEME/$GW_JS" "$TARGET/$GW_JS"
			ln $LN_ARGS "$THEME/$GW_ICON" "$TARGET/$GW_ICON"
			ln $LN_ARGS "$THEME/$GW_LOGO" "$TARGET/$GW_LOGO"
		fi
		
		echo ""
		echo "Complete!"
	fi
}

remove()
{
	set_target
	set_cmd_args

	if [[ $(check_if_themed) == $FALSE ]];
	then
		echo "Nothing to do, no symlinks found in target (Is the theme already removed?)"
	else
		log ""
		if [[ $INTERACTIVE && $(confirm "Deleting Symlinks, Continue?") == $FALSE ]]; then
			echo ""
			exit 1
		else
			echo ""
			rm $RM_ARGS "$TARGET/$GW_CSS"
			rm $RM_ARGS "$TARGET/$GW_JS"
			rm $RM_ARGS "$TARGET/$GW_ICON"
			rm $RM_ARGS "$TARGET/$GW_LOGO"
		fi

		log ""
		if [[ $(confirm "Restoring Original Files, Continue?") == $FALSE ]]; then
			echo ""
			exit 1
		else
			echo ""
			mv $MV_ARGS "$TARGET/$GW_CSS.bak" "$TARGET/$GW_CSS"
			mv $MV_ARGS "$TARGET/$GW_JS.bak" "$TARGET/$GW_JS"
			mv $MV_ARGS "$TARGET/$GW_ICON.bak" "$TARGET/$GW_ICON"
			mv $MV_ARGS "$TARGET/$GW_LOGO.bak" "$TARGET/$GW_LOGO"
		fi

		echo ""
		echo "Complete!"
	fi
}

set_target()
{
	if [[ $TARGET && ( $(check_if_gitweb $TARGET) == $TRUE ) ]]
	then
		log "Using specified install path: '$TARGET'"
		$TARGET="$TARGET/static"
		
		if [[ $INTERACTIVE ]]; then
			if [[ $(confirm "Is this correct?") == $FALSE ]]; then
				echo ""
				exit 1
			fi
		fi
	else
		if [[ $(check_if_gitweb $DEFAULT_TARGET) == $TRUE ]]
		then
			log "Using default install path: '$DEFAULT_TARGET'"
			
			if [[ $INTERACTIVE ]]; then
				if [[ $(confirm "Is this correct?") == $FALSE ]]
				then
					echo ""
					exit 1
				else
					echo ""
					TARGET="$DEFAULT_TARGET/static"
				fi
			fi
		else
			echo "Couldn't find static folder in the install path."
			echo "Are you sure this folder contains gitweb?"
		fi
	fi
}

set_cmd_args()
{
	if [[ $VERBOSE ]];
	then
		MV_ARGS="-v"
		LN_ARGS="-v -s"
		RM_ARGS="-v"
	fi
	
	if [[ $INTERACTIVE ]];
	then
		MV_ARGS="-i"
		LN_ARGS="-i -s"
		RM_ARGS="-i"
	fi
	
	if [[ $INTERACTIVE && $VERBOSE ]];
	then
		MV_ARGS="-i -v"
		LN_ARGS="-i -v -s"
		RM_ARGS="-i -v"
	fi
}

check_if_gitweb()
{
	if [[ -d "$1/static" ]]
	then
		echo $TRUE
	else
		echo $FALSE
	fi
}

check_if_themed()
{

	if [[ -h "$TARGET/$GW_CSS" && \
		  -h "$TARGET/$GW_JS" && \
		  -h "$TARGET/$GW_ICON" && \
		  -h "$TARGET/$GW_LOGO" ]]
	then
		echo $TRUE
	else
		echo $FALSE
	fi
}

confirm()
{
	read -n 1 -p "$1 ([y]es / [n]o) : " REPLY
	
	case $REPLY in
		y|Y)
			echo $TRUE
		;;
		n|N)
			echo $FALSE
		;;
		*)
			echo "You must answer [y]es or [n]o"
			confirm "$1"
		;;
	esac
}

log()
{
	if [[ $VERBOSE ]]; then
		echo "$1"
	fi
}

usage()
{
cat << EOF
Usage: $0 [OPTIONS]

This script will create symlinks to your gitweb install for themeing.
The default location is '/usr/share/gitweb' unless set via -t or --target. 

OPTIONS:
  -v, --verbose       Verbose output
  -i, --interactive   Pauses for confirmation at each step
  -t, --target        Where to create the symlinks, gitweb installation path
  -V, --version       Displays version information
  --install           Adds '.bak' to original files and creates symlinks to new files
  --remove            Deletes the symlinks and restores the original files.
EOF
}



##########################################################
#   Let's Go!
##########################################################
PROG_NAME=$0
PROG_VERSION="0.9.0"
AUTHOR="Kevin Hill <http://github.com/kevinkhill>"

TARGET=
THEME=`pwd`
INTERACTIVE=false
VERBOSE=false

GW_CSS="gitweb.css"
GW_JS="gitweb.js"
GW_ICON="git-favicon.png"
GW_LOGO="git-logo.png"

SHORT_OPTS="hviVt:"
LONG_OPTS="help,verbose,interactive,version,target:,install,remove"
OPTS=$(getopt -o "$SHORT_OPTS" -l "$LONG_OPTS" --name "$0" -- "$@")

readonly TRUE=0
readonly FALSE=1

if [ $? != 0 ]; then
    exit 1
fi

eval set -- "$OPTS"
unset OPTS

if [ $# -eq 0 ]; then
	echo "$0: error - no options specified" >&2
	usage
fi

while [ $# -gt 0 ]; do
	case $1 in
		-h|--help|-\?)
			usage
			exit 0
		;;
		-v|--verbose)
			VERBOSE=true
		;;
		-i|--interactive)
			INTERACTIVE=true
		;;
		-t|--target)
			TARGET=$2
		;;
		-V|--version)
			echo "Gitweb Theme Installer Script - v$PROG_VERSION"
			echo " Author: $AUTHOR"
			echo ""
			echo "Use $TARGET/setup --help for instructions"
		;; 
		--install)
			install
			shift
		;;
		--remove)
			remove
			shift
		;;
		--)
			shift
			break
		;;
		-*)
			echo "$0: error - unrecognized option $1" >&2
			shift
		;;
		*)
			break
		;;
	esac
	shift
done

echo "TARGET=$TARGET"
echo "INTERACTIVE=$INTERACTIVE"
echo "VERBOSE=$VERBOSE"

exit 0
